---
- hosts: compute
  user: vagrant
  sudo: True
  vars_files:
    - ../global_vars.yaml

  tasks:
  - name: ensure apt repo is up to date
    action: apt update-cache=yes

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/installing-ntp.html
  - name: cron job to sync time hourly
    action: template src=templates/timesync dest=/etc/cron.hourly/timesync owner=root group=root mode=0755

#    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/compute-configuring-guest-network.html
#  - include: tasks/bridge.yaml

  # http://www.mirantis.com/blog/openstack-networking-single-host-flatdhcpmanager/
  - name: ensure eth2 is in promiscuous mode
    action: command /sbin/ifconfig eth2 promisc

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/installing-additional-compute-nodes.html
  - name: ensure nova-compute packages are installed
    action: apt pkg=$item
    with_items:
      - python-mysqldb
      - nova-compute-qemu
      - bridge-utils
      - guestmount

  - name: ensure libguest has been updated
    action: command /usr/sbin/update-guestfs-appliance

  - name: ensure nova.conf file is present
    action: template src=templates/nova.conf dest=/etc/nova/nova.conf owner=nova group=nova mode=0640
    notify:
      - restart nova-compute


  handlers:
  - name: restart nova-compute
    action: service name=nova-compute state=restarted
